CFLAGS = -Wall -Werror

CC     = gcc

ALL: ptr_arr ptr_fun ptr_par ptr_var

ptr_arr:
		$(CC) $(CFLAGS) pointers_arrays.c -o ptr_arr

ptr_fun:
		$(CC) $(CFLAGS) pointers_functions.c -o ptr_fun

ptr_par:
		$(CC) $(CFLAGS) pointers_params.c -o ptr_par

ptr_var:
		$(CC) $(CFLAGS) pointers_variables.c -o ptr_var
